### ISSUE TITLE
Getting started is missing a GitHub Pages enable step

### ISSUE THREAD

**Issue by IvanVnucec** [forever-jekyll/forever-jekyll#15]
After forking the repository, user needs to go to Settings -> Pages ->  Source -> Branch: main -> /(root) -> Save, and then wait for Action to finish, then the Jekyll site will be up and running. Otherwise, there will be no site.

Add that to [Getting started](https://github.com/forever-jekyll/forever-jekyll#getting-started) part.

**Comment by forever-jekyll** [comment]
Done. Thanks for the hint :+1:
