### ISSUE TITLE
Navbar looks strange when multiple navigation items are defined

### ISSUE THREAD

**Issue by IvanVnucec** [forever-jekyll/forever-jekyll#18]
![image](https://user-images.githubusercontent.com/50591550/164560447-164c1c8f-40e9-4870-8112-c6926782818f.png)

**Comment by forever-jekyll** [comment]
![image](https://user-images.githubusercontent.com/86324895/164770083-08228697-0c80-4ac0-90b4-00d14ef651a1.png)

Looks okay now?

**Comment by IvanVnucec** [comment]
Oh, I like it!
Maybe just decrease spacing between lines in heading. Looks weird on certain resolution. See below:
![image](https://user-images.githubusercontent.com/50591550/164772955-806cb0a4-5feb-404f-8af8-2456b08be1a6.png)

**Comment by forever-jekyll** [comment]
Gotcha. Will look into it. Thanks :+1:

**Comment by IvanVnucec** [comment]
I now see that I did not respond to your question. I've changed default.html on my fork in order to have more nav list items and longer site name. 
You can see that I've completly changed position of the site name and description. I don't know if those changes would make sense on your repo.

**Comment by forever-jekyll** [comment]
I'll look into those changes and will merge if appropriate. Thanks!
