### ISSUE TITLE
Fix Jekyll build warnings

### ISSUE THREAD

**Issue by IvanVnucec** [forever-jekyll/forever-jekyll#19]
I've forked the repo and created my own GitHub Pages. 
On Jekyll build step, Jekyll had show warnings as:
```
Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
```
```
GitHub Metadata: site.name is set in _config.yml, but many plugins and themes expect site.title to be used instead. To avoid potential inconsistency, Jekyll GitHub Metadata will not set site.title to the repository's name.
```
I've fixed it with these two commits on my repo:
1. https://github.com/IvanVnucec/IvanVnucec.github.io/commit/fa71217d2626be398739a826a845fa705eb28a5f
2. https://github.com/IvanVnucec/IvanVnucec.github.io/commit/2782b5633cd5cc21b7627b3526e9a0faabbdd044

**Comment by forever-jekyll** [comment]
Done. Thanks for pointing this out @IvanVnucec :+1:
