### ISSUE TITLE
click on a tag should show posts by that tag only

### ISSUE THREAD

**Issue by IvanVnucec** [forever-jekyll/forever-jekyll#20]
It lists all tags no matter what tag we've clicked nor what URL we've go to:
1. https://forever-jekyll.github.io/categories/#content
2. https://forever-jekyll.github.io/categories/#demo

**Comment by forever-jekyll** [comment]
This is by design. The categories page is a single page. Clicking on tag will scroll down the page and put that tag in focus. This will only be apparent on a lengthy page.

**Comment by IvanVnucec** [comment]
Thanks. Later I found [discussion ](https://github.com/forever-jekyll/forever-jekyll/discussions/3)page about that.
