### ISSUE TITLE
Support for languages other than lang=en in html tag

### ISSUE THREAD

**Issue by takapiro99** [forever-jekyll/forever-jekyll#7]
In the default template, the lang attribute of html tag is fixed to `lang="en"`.

https://github.com/forever-jekyll/forever-jekyll/blob/970ca1ca433b1c4dcabe4ff453ed3998af1d413b/_layouts/default.html#L2

---

Meanwhile, other github pages official themes can configure it in `_config.yml`. I would be happy to do it this way.

cf. 

https://github.com/pages-themes/slate/blob/a185c0dde883863779be4856421ba0b2390f44a4/_layouts/default.html#L2

https://github.com/jekyll/minima/blob/7a326eb6df07ee6ee5305cfc1b28f7092037e67d/_layouts/default.html#L2

I'm happy if you will consider this.

I am not immediately available, but I can provide PR.
thanks in advance.

**Comment by forever-jekyll** [comment]
@takapiro99 Thank you so much for the suggestion and improvement idea. :+1: 
I've implemented your suggestion. Thanks again! :bowing_man:

**Comment by takapiro99** [comment]
thanks so much ❤️
